# Generated by Django 5.2.13 on 2026-04-23 18:27

import django.db.models.deletion
import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255, verbose_name="Место")),
                ("time", models.TimeField(verbose_name="Время")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Приятная привычка")),
                (
                    "periodicity",
                    models.IntegerField(
                        choices=[(1, "Ежедневно"), (2, "Каждые 2 дня"), (3, "Каждые 3 дня"), (7, "Еженедельно")],
                        default=1,
                        validators=[habits.validators.validate_periodicity],
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение")),
                (
                    "execution_time",
                    models.PositiveIntegerField(
                        validators=[habits.validators.validate_execution_time], verbose_name="Время выполнения (сек)"
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичная")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_to",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["time"],
            },
        ),
    ]
